name: ffmpeg-actions-workflow
on: 
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
         id: [1]
         include:
          - id: 1
            url: https://v7.dious.cc/20220719/f8Y2gPyi/index.m3u8?_=1704112101411
    
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: curl ffmpeg
        shell: cmd
        run: |
          curl https://github.com/GyanD/codexffmpeg/releases/download/6.0/ffmpeg-6.0-full_build.zip -L --output ffmpeg.zip &&^
          7z.exe x ffmpeg.zip
        
#       - name: download m3u8
#         shell: cmd
#         run: |
#             set PATH=^
#             ${{ github.workspace }}\ffmpeg-6.0-full_build\bin;^
#             %PATH%
#             mkdir downloads &&^
#             ffmpeg -http_persistent 0 -protocol_whitelist file,http,https,tcp,tls,crypto -i "${{ github.workspace }}\input.m3u8" "output.mp4" &&^
#             7z a -tzip -v100m downloads\archive.zip output.mp4 &&^
#             dir

      - name: download url with headers
        shell: bash
        run: |
          workspace=$(pwd) && \
          export PATH="$workspace/ffmpeg-6.0-full_build/bin:$PATH" && \
          mkdir -p downloads/${{ matrix.id }} && \
          ffmpeg -i '${{ matrix.url }}' \
          -headers 'authority: v7.dious.cc' \
          -headers 'accept: */*' \
          -headers 'accept-language: en-US,en;q=0.9' \
          -headers 'origin: https://tw.xiaoyakankan.com' \
          -headers 'referer: https://tw.xiaoyakankan.com/' \
          -headers 'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"' \
          -headers 'sec-ch-ua-mobile: ?0' \
          -headers 'sec-ch-ua-platform: "Windows"' \
          -headers 'sec-fetch-dest: empty' \
          -headers 'sec-fetch-mode: cors' \
          -headers 'sec-fetch-site: cross-site' \
          -headers 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' \
          -c:v libx264 -c:a aac \
          "${{ matrix.id }}.mp4" && \
          7z a -tzip -v100m downloads/${{ matrix.id }}/${{ matrix.id }}.zip ${{ matrix.id }}.mp4 && \
          ls
            
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ matrix.id }}
          path: "downloads/${{ matrix.id }}/*"
          
#       - name: Release prebuilt
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "downloads/*"
#           allowUpdates: true
#           token: ${{ secrets.GITHUB_TOKEN }}
