name: ffmpeg-actions-workflow
on: 
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
         id: [1]
         include:
          - id: 1
            url: https://s-cloudfront.cdn.ap.panopto.com/sessions/b9ff719f-3532-4e72-aef4-afdc007c886d/22a1c846-7c71-4862-9f8c-afdc007c8877-be8c28d1-793a-4423-9fad-afdc0085f109.hls/master.m3u8?InvocationID=09e0705a-c03a-ee11-aa07-064de5ffa912&tid=00000000-0000-0000-0000-000000000000&StreamID=32852752-538b-48a4-8119-afdc007c890f&ServerName=polyu.ap.panopto.com
    
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: curl ffmpeg
        shell: cmd
        run: |
          curl https://github.com/GyanD/codexffmpeg/releases/download/6.0/ffmpeg-6.0-full_build.zip -L --output ffmpeg.zip &&^
          7z.exe x ffmpeg.zip
        
#       - name: download m3u8
#         shell: cmd
#         run: |
#             set PATH=^
#             ${{ github.workspace }}\ffmpeg-6.0-full_build\bin;^
#             %PATH%
#             mkdir downloads &&^
#             ffmpeg -http_persistent 0 -protocol_whitelist file,http,https,tcp,tls,crypto -i "${{ github.workspace }}\input.m3u8" "output.mp4" &&^
#             7z a -tzip -v100m downloads\archive.zip output.mp4 &&^
#             dir

      - name: download url with headers
        shell: bash
        run: |
          workspace=$(pwd) && \
          export PATH="$workspace/ffmpeg-6.0-full_build/bin:$PATH" && \
          mkdir -p downloads/${{ matrix.id }} && \
          ffmpeg.exe -i '${{ matrix.url }}' \
          -c copy \
          "${{ matrix.id }}.mp4" && \
          7z a -tzip -v100m downloads/${{ matrix.id }}/${{ matrix.id }}.zip ${{ matrix.id }}.mp4 && \
          ls
            
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ matrix.id }}
          path: "downloads/${{ matrix.id }}/*"
          
#       - name: Release prebuilt
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "downloads/*"
#           allowUpdates: true
#           token: ${{ secrets.GITHUB_TOKEN }}
