name: ffmpeg-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: curl ffmpeg
        shell: cmd
        run: |
          curl https://github.com/GyanD/codexffmpeg/releases/download/6.0/ffmpeg-6.0-full_build.zip -L --output ffmpeg.zip &&^
          7z.exe x ffmpeg.zip
        
#       - name: download m3u8
#         shell: cmd
#         run: |
#             set PATH=^
#             ${{ github.workspace }}\ffmpeg-6.0-full_build\bin;^
#             %PATH%
#             mkdir downloads &&^
#             ffmpeg -http_persistent 0 -protocol_whitelist file,http,https,tcp,tls,crypto -i "${{ github.workspace }}\input.m3u8" "output.mp4" &&^
#             7z a -tzip -v100m downloads\archive.zip output.mp4 &&^
#             dir

      - name: download url with headers
        shell: bash
        run: |
          workspace=$(pwd) && \
          export PATH="$workspace/ffmpeg-6.0-full_build/bin:$PATH" && \
          mkdir -p downloads && \
          ffmpeg.exe -i 'http://103.151.151.47/upgcxcode/93/34/227273493/227273493-1-160.mp4?e=ig8euxZM2rNcNbRV7bdVhwdlhWdjhwdVhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IMvNC8xNbLEkF6MuwLStj8fqJ0EkX1ftx7Sqr_aio8_&ua=tvproj&uipk=5&nbs=1&deadline=1682349443&gen=playurlv2&os=bcache&oi=391865670&trid=0000de591d890efd42318fe1ff466b6ae064T&mid=0&upsig=4986b4ab58dbf03f031842da981c98b8&uparams=e,ua,uipk,nbs,deadline,gen,os,oi,trid,mid&cdnid=9596&bvc=vod&nettype=0&bw=106464&orderid=0,2&buvid=&build=0&mobi_app=&logo=80000000' \
          -headers 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
          -headers 'Accept-Language: en-US,en;q=0.9' \
          -headers 'Cache-Control: no-cache' \
          -headers 'Connection: keep-alive' \
          -headers 'Pragma: no-cache' \
          -headers 'Upgrade-Insecure-Requests: 1' \
          -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36' "3.mp4" && \
          7z a -tzip -v100m downloads/archive.zip 3.mp4 && \
          ls
            
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "downloads/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
